---
title: "AgreementSubset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load in the data and adjust the coding of conditions.

```{r}
library(tidyr)
library(dplyr)

rt.rdata <- read.csv("data/AgreementSet.csv", header=TRUE)
rt.data <- rt.rdata %>% filter(RT<=7000) %>% 
                        filter(ROI%in%c(-3,-2,-1,0,1,2)) %>%
                        rename(participant = MD5)

rt.data$Type <- as.character(rt.data$Type) # Just in case it's automatically read as a factor

# Maybe this should all just be a recode call?
rt.data$Type[rt.data$Type == "AGREE"] <- "AGREE_G"

rt.data <- rt.data %>% separate(Type, c("Type", "pGram"), sep="_")

rt.data$pGram[rt.data$pGram == "UAMB"] <- "G"
rt.data$pGram[rt.data$pGram == "AMB"] <- "U"
rt.data$pGram[rt.data$pGram == "UNG"] <- "U"

rt.data$pGram <- as.factor(rt.data$pGram)
rt.data$Type <- as.factor(rt.data$Type)
```

Prep data for hypothesis testing.

``` {r}

# Sum coding for the position factor
rt.ht_data <- rt.data %>% subset(rt.data$ROI >= 0) # critical + spillover data only

rt.ht_data$position <- droplevels(as.factor(rt.ht_data$ROI))

contrasts(rt.ht_data$position) <- contr.sum(3)/2
contrasts(rt.ht_data$position)

saveRDS(rt.ht_data, "datasets/agreement_data.rds")

```

``` {r}

rt.ht_data <- readRDS("datasets/agreement_data.rds")

summary(rt.ht_data)
head(subset(rt.ht_data, is.na(rt.ht_data$pGram)))
```

``` {r}

library(lme4)
library(lmerTest)

model.freq.prereg <- lmer(RT ~ pGram * Type * position + (1 + pGram * Type * position || participant) + (1 + pGram * Type * position || item), 
                          data = rt.ht_data,
                          REML = FALSE, 
                          control=lmerControl(optimizer="bobyqa", 
                                              optCtrl=list(maxfun=200000)))

saveRDS(model.freq.prereg, "models/agreement_fmodel_prereg.rds")

```
``` {r}
model.freq.trialnum <- lmer(RT ~ pGram * Type * position + trialnumber + (1 + pGram * Type * position || participant) + (1 + pGram * Type * position || item), 
                          data = rt.ht_data,
                          REML = FALSE, 
                          control=lmerControl(optimizer="bobyqa", 
                                              optCtrl=list(maxfun=200000)))

saveRDS(model.freq.trialnum, "models/agreement_fmodel_trialnum.rds")
```


```{r}
library(brms)
model.prior1.prereg <- readRDS("models/agreement_bmodel_prior1.rds")
summary(model.prior1.prereg)

model.prior1.trialnum <- readRDS("models/agreement_bmodel_prior1_trialnum.rds")
summary(model.prior1.trialnum)
```



```{r}
library(bayestestR)
library(ggplot2)
library(dplyr)
library(stringr)

model.prior1.prereg.hdi <- hdi(model.prior1.prereg, ci=0.95, effects="all")

ggplot(subset(model.prior1.prereg.hdi, str_detect(Parameter, 'b_'))) +
  geom_linerange(mapping=aes(x = Parameter,
                             ymin = CI_low,
                             ymax = CI_high)) + 
  geom_hline(yintercept=0, linetype="dashed") +
  theme_classic() + theme(axis.text.x=element_text(angle=45, hjust=1))

```

``` {r}
model.prior1.trialnum.hdi <- hdi(model.prior1.trialnum, ci=0.95, effects="all")

ggplot(subset(model.prior1.trialnum.hdi, str_detect(Parameter, 'b_'))) +
  geom_linerange(mapping=aes(x = Parameter,
                             ymin = CI_low,
                             ymax = CI_high)) + 
  geom_hline(yintercept=0, linetype="dashed") +
  theme_classic() + theme(axis.text.x=element_text(angle=45, hjust=1))

```

``` {r}
posterior.prereg <- posterior_samples(model.prior1.prereg)
posterior.prereg <- subset(posterior.prereg, select=!str_detect(colnames(posterior.prereg), "r_position"))

posterior.trialnum <- posterior_samples(model.prior1.trialnum)
posterior.trialnum <- subset(posterior.trialnum, select=!str_detect(colnames(posterior.trialnum), "r_position"))
```

``` {r}
# Effect size by position

bypos_analysis <- function(posterior) {
  fixed_effs <- posterior %>%
              mutate(GPE_0 = b_pGramU + `b_TypeNPZ:pGramU` + 0.5 * `b_pGramU:position1` + 0.5 * `b_TypeNPZ:pGramU:position1`,
                     GPE_1 = b_pGramU + `b_TypeNPZ:pGramU` + 0.5 * `b_pGramU:position2` + 0.5 * `b_TypeNPZ:pGramU:position2`,
                     GPE_2 = b_pGramU + `b_TypeNPZ:pGramU` - 0.5 * `b_pGramU:position1` - 0.5 * `b_TypeNPZ:pGramU:position1` - 0.5 * `b_pGramU:position2` - 0.5 * `b_TypeNPZ:pGramU:position2`,
                     Agr_0 = b_pGramU + 0.5 * `b_pGramU:position1`,
                     Agr_1 = b_pGramU + 0.5 * `b_pGramU:position2`,
                     Agr_2 = b_pGramU - 0.5 * `b_pGramU:position1` - 0.5 * `b_pGramU:position2`) %>%
              gather("effect", "size", c("GPE_0", "GPE_1", "GPE_2", "Agr_0", "Agr_1", "Agr_2")) %>%
              group_by(effect) %>%
              summarize(mean=mean(size),
                        lower = quantile(size, 0.025)[[1]],
                        upper = quantile(size, 0.975)[[1]]) %>%
              separate("effect", c("type", "position"), sep ="_") 
  return(fixed_effs)
}


saveRDS(bypos_analysis(posterior.prereg), "datasets/agreement.prereg.by_pos.rds")
saveRDS(bypos_analysis(posterior.trialnum), "datasets/agreement.trialnum.by_pos.rds")
```

``` {r}

fixed_effs.prereg <- readRDS("datasets/agreement.prereg.by_pos.rds")
# Ploting
ggplot(fixed_effs.prereg, aes(x=position, color=type, y=mean)) +
  geom_linerange(mapping=aes(ymin=lower,
                             ymax=upper)) + 
  geom_point() +
  scale_color_discrete(labels=c("Agr"="Agreement Error", "GPE"="Garden Path")) +
  theme_classic() + labs(x="Spillover Position", y="Effect of Percieved Ungrammaticality", color="Type")

```

``` {r}

fixed_effs.trialnum <- readRDS("datasets/agreement.trialnum.by_pos.rds")
# Ploting
ggplot(fixed_effs.trialnum, aes(x=position, color=type, y=mean)) +
  geom_linerange(mapping=aes(ymin=lower,
                             ymax=upper)) + 
  geom_point() +
  scale_color_discrete(labels=c("Agr"="Agreement Error", "GPE"="Garden Path")) +
  theme_classic() + labs(x="Spillover Position", y="Effect of Percieved Ungrammaticality", color="Type", title="corrected for trial number")

```

``` {r}
library(reshape2)

# By Item
byitem_analysis <- function(posterior) {
  print(colnames(posterior))
  cns = c()
  ran_eff <- posterior
  for(i in 1:24) {
    gram_name <- paste0("r_item[", toString(i),",pGramU]")
    inter_name <- paste0("r_item[", i, ",TypeNPZ:pGramU]")
    ran_eff <- ran_eff %>% mutate("GPE_{i}" := b_pGramU + `b_TypeNPZ:pGramU` + !!as.name(gram_name) + !!as.name(inter_name),
                          "Agr_{i}" := b_pGramU + !!as.name(gram_name)) 
    cns <- append(cns, c(paste0("GPE_", toString(i)), paste0("Agr_", toString(i))))
  }
              
  ran_eff <- ran_eff %>% gather("item", "effect", all_of(cns)) %>%
              group_by(item) %>%
              summarize(mean=mean(effect),
                        lower = quantile(effect, 0.025)[[1]],
                        upper = quantile(effect, 0.975)[[1]]) %>%
              separate("item", c("type", "item_num"), sep ="_") 
  return(ran_eff) 
}
saveRDS(byitem_analysis(posterior.prereg), "datasets/agreement.prereg.by_item.rds")
saveRDS(byitem_analysis(posterior.trialnum), "datasets/agreement.trialnum.by_item.rds")

```

``` {r}

ran_effs <- readRDS("datasets/agreement.prereg.by_item.rds")
ran_effs

ggplot(ran_effs, aes(x=as.numeric(item_num), color=type, y=mean)) +
  geom_linerange(mapping=aes(ymin=lower,
                             ymax=upper)) + 
  geom_point() +
  scale_color_discrete(labels=c("Agr"="Agreement Error", "GPE"="Garden Path")) +
  theme_classic() + labs(x="Item", y="Effect of Percieved Ungrammaticality", color="Type")


```

``` {r}

ran_effs <- readRDS("datasets/agreement.trialnum.by_item.rds")
ran_effs

ggplot(ran_effs, aes(x=as.numeric(item_num), color=type, y=mean)) +
  geom_linerange(mapping=aes(ymin=lower,
                             ymax=upper)) + 
  geom_point() +
  scale_color_discrete(labels=c("Agr"="Agreement Error", "GPE"="Garden Path")) +
  theme_classic() + labs(x="Item", y="Effect of Percieved Ungrammaticality", color="Type", title="corrected for trial number")


```

``` {r}
# By Item
byboth_analysis <- function(posterior) {
  print(colnames(posterior))
  cns = c()
  ran_eff <- posterior
  for(i in 1:24) {
    gram_name <- paste0("r_item[", toString(i),",pGramU]")
    inter_name <- paste0("r_item[", i, ",TypeNPZ:pGramU]")
    ran_eff <- ran_eff %>% mutate("GPE_{i}" := b_pGramU + `b_TypeNPZ:pGramU` + !!as.name(gram_name) + !!as.name(inter_name),
                                  "Agr_{i}" := b_pGramU + !!as.name(gram_name)) 
    
    gpe_avg <- paste0("GPE_", toString(i))
    agr_avg <- paste0("Agr_", toString(i))
    
    # For RE structure (1 + pGram * Type + position || item) - update as needed if using a more rich RE structure with position:Type interactions!
    ran_eff <- ran_eff %>% mutate("GPE_{i}_0" := !!as.name(gpe_avg) + 0.5 * `b_pGramU:position1` + 0.5 * `b_TypeNPZ:pGramU:position1`,
                                  "GPE_{i}_1" := !!as.name(gpe_avg) + 0.5 * `b_pGramU:position2` + 0.5 * `b_TypeNPZ:pGramU:position2`,
                                  "GPE_{i}_2" := !!as.name(gpe_avg) - 0.5 * `b_pGramU:position1` - 0.5 * `b_TypeNPZ:pGramU:position1` -  0.5 * `b_pGramU:position2` - 0.5 * `b_TypeNPZ:pGramU:position2`,
                                  "Agr_{i}_0" := !!as.name(agr_avg) + 0.5 * `b_pGramU:position1`,
                                  "Agr_{i}_1" := !!as.name(agr_avg) + 0.5 * `b_pGramU:position2`,
                                  "Agr_{i}_2" := !!as.name(agr_avg) - 0.5 * `b_pGramU:position2`- 0.5 * `b_pGramU:position2`
                                  ) 
    for(i in 0:2) {
      cns <- append(cns, c(paste0("GPE_", toString(i), "_", toString(j)), paste0("Agr_", toString(i), "_", toString(j))))
    }
  }
              
  ran_eff <- ran_eff %>% gather("item", "effect", all_of(cns)) %>%
              group_by(item) %>%
              summarize(mean=mean(effect),
                        lower = quantile(effect, 0.025)[[1]],
                        upper = quantile(effect, 0.975)[[1]]) %>%
              separate("item", c("type", "item_num", "position"), sep ="_") 
  return(ran_eff) 
}
saveRDS(byboth_analysis(posterior.prereg), "datasets/agreement.prereg.by_both.rds")
saveRDS(byboth_analysis(posterior.trialnum), "datasets/agreement.trialnum.by_both.rds")
```

``` {r}
# Surprisal Correlations
library(ggplot2)
surps.lstm <- readRDS("datasets/agreement_data.lstm.rds")

surps.lstm.corrplot <- surps.lstm %>% gather("surp_p", "surprisal", c("surprisal_lstm", "surprisal_lstm_p1", "surprisal_lstm_p2", "surprisal_lstm_p3")) %>%
  group_by(item, Type, pGram, surp_p) %>%
  summarize(surprisal=mean(surprisal)) %>%
  spread(pGram, surprisal) %>%
  mutate(ugram_eff = U-G)

ran_effs <- readRDS("datasets/agreement.trialnum.by_item.rds")
ran_effs

ran_effs$type <- recode(ran_effs$type, "Agr" = "AGREE", "GPE" = "NPZ")

surps.lstm.corrplot <- merge(x=surps.lstm.corrplot, y=ran_effs, by.x=c("item", "Type"), by.y=c("item_num", "type"), all.x=TRUE)

ggplot(data=surps.lstm.corrplot, aes(x=ugram_eff, y=mean, color=Type)) + geom_linerange(aes(ymin=lower, ymax=upper)) + geom_point() + facet_wrap(~surp_p) + labs(y="Human RT", x="Difference in Surprisal")

```

```{r}
surps.gpt <- readRDS("datasets/agreement_data.gpt2.rds")

surps.gpt.corrplot <- surps.gpt %>% gather("surp_p", "surprisal", c("surprisal_gpt2", "surprisal_gpt2_p1", "surprisal_gpt2_p2", "surprisal_gpt2_p3")) %>%
  group_by(item, Type, pGram, surp_p) %>%
  summarize(surprisal=mean(surprisal)) %>%
  spread(pGram, surprisal) %>%
  mutate(ugram_eff = U-G)

ran_effs <- readRDS("datasets/agreement.trialnum.by_item.rds")
ran_effs

ran_effs$type <- recode(ran_effs$type, "Agr" = "AGREE", "GPE" = "NPZ")

surps.gpt.corrplot <- merge(x=surps.gpt.corrplot, y=ran_effs, by.x=c("item", "Type"), by.y=c("item_num", "type"), all.x=TRUE)

ggplot(data=surps.gpt.corrplot, aes(x=ugram_eff, y=mean, color=Type)) + geom_linerange(aes(ymin=lower, ymax=upper)) + geom_point() + facet_wrap(~surp_p) + labs(y="Human RT", x="Difference in Surprisal")

```