---
title: "run"
author: "SAP"
date: "2022/6/3"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("util.R")
```

```{r ClassicGP}
rt.data <- read.csv("ClassicGardenPathSet.csv", header=TRUE) %>%
  filter(RT <= 7000) %>% filter(RT>0) %>% mutate(participant=MD5)
rt.data$Sentence <- str_replace_all(rt.data$Sentence, "%2C", ",")
rt.data$EachWord <- str_replace_all(rt.data$EachWord, "%2C", ",")
rt.data$word <-  tolower(ifelse(substring(rt.data$EachWord,nchar(rt.data$EachWord),nchar(rt.data$EachWord))%in%c(".",","),substring(rt.data$EachWord,1,nchar(rt.data$EachWord)-1),rt.data$EachWord))
fit_P0 <- readRDS("fitClassicGP_prior1_P0.RDS")
fit_P1 <- readRDS("fitClassicGP_prior1_P1.RDS")
fit_P2 <- readRDS("fitClassicGP_prior1_P2.RDS")
reshape_item_output_P0 <- reshape_item_dat(fit_P0, 'item')
reshape_item_output_P1 <- reshape_item_dat(fit_P1, 'item')
reshape_item_output_P2 <- reshape_item_dat(fit_P2, 'item')
reshape_item_output <- rbind(reshape_item_output_P0,reshape_item_output_P1,reshape_item_output_P2)%>%mutate(ROI = rep(c("0","1","2"),each=nrow(reshape_item_output_P0)))
reshape_item_output$item <- as.numeric(reshape_item_output$item)
rm(list=c(fit_P0,fit_P1,fit_P0,reshape_item_output_P0,reshape_item_output_P1,reshape_item_output_P2))
#ClassicGP
by_item <- reshape_item_output %>%
  mutate(GPE_MVRR = b_AMBUAMB + r_AMBUAMB,
         GPE_NPS = b_AMBUAMB + `b_AMBUAMB:SZM1` + r_AMBUAMB + `r_AMBUAMB:SZM1`,
         GPE_NPZ = b_AMBUAMB + `b_AMBUAMB:SZM2` + r_AMBUAMB + `r_AMBUAMB:SZM2`
  ) %>%
  select(`.chain`, `.draw`, `.iteration`, item, ROI, GPE_MVRR, GPE_NPS, GPE_NPZ) %>%
  gather(key = 'coef', value = 'val', GPE_MVRR, GPE_NPS, GPE_NPZ) %>%
  group_by(item, ROI , coef) %>%
  summarise(mean = mean(val),
            lower = quantile(val, 0.025)[[1]],
            upper = quantile(val, 0.975)[[1]])
by_construction <- reshape_item_output[,c('.draw','ROI',colnames(reshape_item_output)[str_detect(colnames(reshape_item_output),'b')])] %>% unique() %>%
  mutate(GPE_MVRR = b_AMBUAMB,
         GPE_NPS = b_AMBUAMB+`b_AMBUAMB:SZM1`,
         GPE_NPZ = b_AMBUAMB+`b_AMBUAMB:SZM2`) %>%
  select(ROI,GPE_MVRR,GPE_NPS,GPE_NPZ) %>% gather(key='coef',value='val',GPE_MVRR, GPE_NPS, GPE_NPZ)%>%group_by(ROI,coef)%>%
  summarise(mean=mean(val),
            lower=quantile(val,0.025)[[1]],
            upper=quantile(val,0.975)[[1]])
by_item_surprisalmerged <- merge_surprisal(rt.data,by_item,"ClassicGP")
Plot_empirical_construction_level(by_construction,"ClassicGP")
Plot_itemwise_by_magnitude(by_item,"ClassicGP",ROI=0)
Plot_itemwise_by_magnitude(by_item,"ClassicGP",ROI=1)
Plot_itemwise_by_magnitude(by_item,"ClassicGP",ROI=2)
Plot_humanresults_surprisaldiff_correlation(by_item_surprisalmerged,0)
PredictedRT_df <- Predicting_RT_with_spillover_refactored(rt.data,"ClassicGP")
rt.data <- read.csv("RelativeClauseSet.csv", header=TRUE) %>%
  filter(RT <= 7000) %>% filter(RT>0) %>% mutate(participant=MD5)
rt.data$Sentence <- str_replace_all(rt.data$Sentence, "%2C", ",")
rt.data$EachWord <- str_replace_all(rt.data$EachWord, "%2C", ",")
rt.data$word <-  tolower(ifelse(substring(rt.data$EachWord,nchar(rt.data$EachWord),nchar(rt.data$EachWord))%in%c(".",","),substring(rt.data$EachWord,1,nchar(rt.data$EachWord)-1),rt.data$EachWord))
fit_P0 <- readRDS("fitRelativeClause_prior1_P0.RDS")
fit_P1 <- readRDS("fitRelativeClause_prior1_P1.RDS")
fit_P2 <- readRDS("fitRelativeClause_prior1_P2.RDS")
reshape_item_output_P0 <- reshape_item_dat(fit_P0, 'item')
reshape_item_output_P1 <- reshape_item_dat(fit_P1, 'item')
reshape_item_output_P2 <- reshape_item_dat(fit_P2, 'item')
reshape_item_output <- rbind(reshape_item_output_P0,reshape_item_output_P1,reshape_item_output_P2)%>%mutate(ROI = rep(c("0","1","2"),each=nrow(reshape_item_output_P0)))
reshape_item_output$item <- as.numeric(reshape_item_output$item)
rm(list=c(fit_P0,fit_P1,fit_P0,reshape_item_output_P0,reshape_item_output_P1,reshape_item_output_P2))
by_item <- reshape_item_output %>%
  mutate(RC = b_Type_num + r_Type_num) %>%
  select(`.chain`, `.draw`, `.iteration`, item, ROI, RC) %>%
  gather(key = 'coef', value = 'val', RC) %>%
  group_by(item, ROI , coef) %>%
  summarise(mean = mean(val),
            lower = quantile(val, 0.025)[[1]],
            upper = quantile(val, 0.975)[[1]]) %>% mutate(coef='RC')
by_construction <- reshape_item_output[,c('.draw','ROI',colnames(reshape_item_output)[str_detect(colnames(reshape_item_output),'b')])] %>% unique() %>%
  mutate(RC = b_Type_num) %>%
  select(ROI,RC) %>% gather(key='coef',value='val',RC)%>%group_by(ROI,coef)%>%
  summarise(mean=mean(val),
            lower=quantile(val,0.025)[[1]],
            upper=quantile(val,0.975)[[1]])
by_item_surprisalmerged <- merge_surprisal(rt.data,by_item,"RelativeClause")
Plot_empirical_construction_level(by_construction,"RelativeClause")
Plot_itemwise_by_magnitude(by_item,"RelativeClause",ROI=0)
Plot_itemwise_by_magnitude(by_item,"RelativeClause",ROI=1)
Plot_itemwise_by_magnitude(by_item,"RelativeClause",ROI=2)
Plot_humanresults_surprisaldiff_correlation(by_item_surprisalmerged,0)
PredictedRT_df <- Predicting_RT_with_spillover_refactored(rt.data,"RelativeClause")
```


```{r RelativeClause}
rt.data <- read.csv("RelativeClauseSet.csv", header=TRUE) %>%
  filter(RT <= 7000) %>% filter(RT>0) %>% mutate(participant=MD5)
rt.data$Sentence <- str_replace_all(rt.data$Sentence, "%2C", ",")
rt.data$EachWord <- str_replace_all(rt.data$EachWord, "%2C", ",")
rt.data$word <-  tolower(ifelse(substring(rt.data$EachWord,nchar(rt.data$EachWord),nchar(rt.data$EachWord))%in%c(".",","),substring(rt.data$EachWord,1,nchar(rt.data$EachWord)-1),rt.data$EachWord))
fit_P0 <- readRDS("fitRelativeClause_prior1_P0.RDS")
fit_P1 <- readRDS("fitRelativeClause_prior1_P1.RDS")
fit_P2 <- readRDS("fitRelativeClause_prior1_P2.RDS")
reshape_item_output_P0 <- reshape_item_dat(fit_P0, 'item')
reshape_item_output_P1 <- reshape_item_dat(fit_P1, 'item')
reshape_item_output_P2 <- reshape_item_dat(fit_P2, 'item')
reshape_item_output <- rbind(reshape_item_output_P0,reshape_item_output_P1,reshape_item_output_P2)%>%mutate(ROI = rep(c("0","1","2"),each=nrow(reshape_item_output_P0)))
reshape_item_output$item <- as.numeric(reshape_item_output$item)
rm(list=c(fit_P0,fit_P1,fit_P0,reshape_item_output_P0,reshape_item_output_P1,reshape_item_output_P2))
by_item <- reshape_item_output %>%
  mutate(RC = b_Type_num + r_Type_num) %>%
  select(`.chain`, `.draw`, `.iteration`, item, ROI, RC) %>%
  gather(key = 'coef', value = 'val', RC) %>%
  group_by(item, ROI , coef) %>%
  summarise(mean = mean(val),
            lower = quantile(val, 0.025)[[1]],
            upper = quantile(val, 0.975)[[1]]) %>% mutate(coef='RC')
by_construction <- reshape_item_output[,c('.draw','ROI',colnames(reshape_item_output)[str_detect(colnames(reshape_item_output),'b')])] %>% unique() %>%
  mutate(RC = b_Type_num) %>%
  select(ROI,RC) %>% gather(key='coef',value='val',RC)%>%group_by(ROI,coef)%>%
  summarise(mean=mean(val),
            lower=quantile(val,0.025)[[1]],
            upper=quantile(val,0.975)[[1]])
by_item_surprisalmerged <- merge_surprisal(rt.data,by_item,"RelativeClause")
Plot_empirical_construction_level(by_construction,"RelativeClause")
Plot_itemwise_by_magnitude(by_item,"RelativeClause",ROI=0)
Plot_itemwise_by_magnitude(by_item,"RelativeClause",ROI=1)
Plot_itemwise_by_magnitude(by_item,"RelativeClause",ROI=2)
Plot_humanresults_surprisaldiff_correlation(by_item_surprisalmerged,0)
PredictedRT_df <- Predicting_RT_with_spillover_refactored(rt.data,"RelativeClause")
```

```{AttachmentAmbiguity}
rt.data <- read.csv("AttachmentAmbiguitySet.csv", header=TRUE) %>%
  filter(RT <= 7000) %>% filter(RT>0) %>% mutate(participant=MD5)
rt.data$Sentence <- str_replace_all(rt.data$Sentence, "%2C", ",")
rt.data$EachWord <- str_replace_all(rt.data$EachWord, "%2C", ",")
rt.data$word <-  tolower(ifelse(substring(rt.data$EachWord,nchar(rt.data$EachWord),nchar(rt.data$EachWord))%in%c(".",","),substring(rt.data$EachWord,1,nchar(rt.data$EachWord)-1),rt.data$EachWord))
fit_P0 <- readRDS("fitAttachmentAmbiguity_prior1_P0.RDS")
fit_P1 <- readRDS("fitAttachmentAmbiguity_prior1_P1.RDS")
fit_P2 <- readRDS("fitAttachmentAmbiguity_prior1_P2.RDS")
reshape_item_output_P0 <- reshape_item_dat(fit_P0, 'item')
reshape_item_output_P1 <- reshape_item_dat(fit_P1, 'item')
reshape_item_output_P2 <- reshape_item_dat(fit_P2, 'item')
reshape_item_output <- rbind(reshape_item_output_P0,reshape_item_output_P1,reshape_item_output_P2)%>%mutate(ROI = rep(c("0","1","2"),each=nrow(reshape_item_output_P0)))
reshape_item_output$item <- as.numeric(reshape_item_output$item)
rm(list=c(fit_P0,fit_P1,fit_P0,reshape_item_output_P0,reshape_item_output_P1,reshape_item_output_P2))
by_item <- reshape_item_output %>%
  mutate(GPE_high = -b_ambiguity + (-1/2)*b_height -r_ambiguity + (-1/2)*r_height,
         GPE_low = -b_ambiguity + (1/2)*b_height -r_ambiguity + (1/2)*r_height)  %>%
  select(`.chain`, `.draw`, `.iteration`, item, ROI, RC) %>%
  gather(key = 'coef', value = 'val', RC) %>%
  group_by(item, ROI , coef) %>%
  summarise(mean = mean(val),
            lower = quantile(val, 0.025)[[1]],
            upper = quantile(val, 0.975)[[1]])
by_construction <- reshape_item_output[,c('.draw','ROI',colnames(reshape_item_output)[str_detect(colnames(reshape_item_output),'b')])] %>% unique() %>%
  mutate(GPE_high = -b_ambiguity + (-1/2)*b_height,
         GPE_low = -b_ambiguity + (1/2)*b_height) %>%
  select(ROI,RC) %>% gather(key='coef',value='val',RC)%>%group_by(ROI,coef)%>%
  summarise(mean=mean(val),
            lower=quantile(val,0.025)[[1]],
            upper=quantile(val,0.975)[[1]])
by_item_surprisalmerged <- merge_surprisal(rt.data,by_item,"AttachmentAmbiguity")
Plot_empirical_construction_level(by_construction,"AttachmentAmbiguity")
Plot_itemwise_by_magnitude(by_item,"AttachmentAmbiguity",ROI=0)
Plot_itemwise_by_magnitude(by_item,"AttachmentAmbiguity",ROI=1)
Plot_itemwise_by_magnitude(by_item,"AttachmentAmbiguity",ROI=2)
Plot_humanresults_surprisaldiff_correlation(by_item_surprisalmerged,0)
PredictedRT_df <- Predicting_RT_with_spillover_refactored(rt.data,"AttachmentAmbiguity")
```

```{r Agreement}
rt.data <- read.csv("RelativeClauseSet.csv", header=TRUE) %>%
  filter(RT <= 7000) %>% filter(RT>0) %>% mutate(participant=MD5)
rt.data$Sentence <- str_replace_all(rt.data$Sentence, "%2C", ",")
rt.data$EachWord <- str_replace_all(rt.data$EachWord, "%2C", ",")
rt.data$word <-  tolower(ifelse(substring(rt.data$EachWord,nchar(rt.data$EachWord),nchar(rt.data$EachWord))%in%c(".",","),substring(rt.data$EachWord,1,nchar(rt.data$EachWord)-1),rt.data$EachWord))
fit <- readRDS("fitAgreement_prior1.RDS")
reshape_item_output <- reshape_item_dat(fit, 'item')
reshape_item_output$item <- as.numeric(reshape_item_output$item)
rm(list=c(fit))
by_item <- reshape_item_output %>%
  mutate(GPE = b_pGramU + b_TypeNPZ:pGramU + r_pGramU + r_TypeNPZ:pGramU,
         Agr = b_pGramU + r_pGramU,
         GPE_0 = GPE + 0.5*`b_pGramU:position1` + 0.5 * `b_TypeNPZ:pGramU:position1` + 0.5*`r_pGramU:position1` + 0.5*`r_TypeNPZ:pGramU:position1`,
         GPE_1 = GPE + 0.5*`b_pGramU:position2` + 0.5 * `b_TypeNPZ:pGramU:position2` + 0.5*`r_pGramU:position2` + 0.5*`r_TypeNPZ:pGramU:position2`,
         GPE_2 = GPE  - 0.5 * `b_pGramU:position1` - 0.5 * `b_TypeNPZ:pGramU:position1` -  0.5 * `b_pGramU:position2` - 0.5 * `b_TypeNPZ:pGramU:position2`- 0.5 * `r_pGramU:position1` - 0.5 * `r_TypeNPZ:pGramU:position1` -  0.5 * `r_pGramU:position2` - 0.5 * `r_TypeNPZ:pGramU:position2`,
         Agr_0 = Agr + 0.5 * `b_pGramU:position1` + 0.5 * `r_pGramU:position1`,
         Agr_1 = Agr + 0.5 * `b_pGramU:position2` + 0.5 * `r_pGramU:position2`,
         Agr_2 = Agr  - 0.5 * `b_pGramU:position1`- 0.5 * `b_pGramU:position2` - 0.5 * `r_pGramU:position1`- 0.5 * `r_pGramU:position2`
  ) %>%
  select(`.chain`, `.draw`, `.iteration`, item, GPE, Agr, GPE_0, GPE_1, GPE_2, Agr_0, Agr_1, Agr_2) %>%
  gather(key = 'coef', value = 'val', GPE, Agr, GPE_0, GPE_1, GPE_2, Agr_0, Agr_1, Agr_2) %>%
  group_by(item, coef) %>%
  summarise(mean = mean(val),
            lower = quantile(val, 0.025)[[1]],
            upper = quantile(val, 0.975)[[1]])%>%separate(coef,c('coef','ROI'),sep='_')
by_construction <- reshape_item_output[,c('.draw',colnames(reshape_item_output)[str_detect(colnames(reshape_item_output),'b')])] %>% unique() %>%
  mutate(GPE_0 = b_pGramU + b_TypeNPZ:pGramU + 0.5*`b_pGramU:position1` + 0.5 * `b_TypeNPZ:pGramU:position1`,
         GPE_1 = b_pGramU + b_TypeNPZ:pGramU + 0.5*`b_pGramU:position2` + 0.5 * `b_TypeNPZ:pGramU:position2` ,
         GPE_2 = b_pGramU + b_TypeNPZ:pGramU - 0.5 * `b_pGramU:position1` - 0.5 * `b_TypeNPZ:pGramU:position1` -  0.5 * `b_pGramU:position2` - 0.5 * `b_TypeNPZ:pGramU:position2`,
         Agr_0 = b_pGramU + 0.5 * `b_pGramU:position1`,
         Agr_1 = b_pGramU + 0.5 * `b_pGramU:position2`,
         Agr_2 = b_pGramU - 0.5 * `b_pGramU:position1`- 0.5 * `b_pGramU:position2`) %>%
  select(GPE_0,GPE_1,GPE_2,Agr_0,Agr_1,Agr_2) %>% gather(key='coef',value='val')%>%group_by(coef)%>%
  summarise(mean=mean(val),
            lower=quantile(val,0.025)[[1]],
            upper=quantile(val,0.975)[[1]])%>%separate(coef, c('coef', 'ROI'), sep= '_')
Plot_empirical_construction_level(by_construction,"Agreement")
Plot_itemwise_by_magnitude(by_item,"Agreement",ROI=0)
Plot_itemwise_by_magnitude(by_item,"Agreement",ROI=1)
Plot_itemwise_by_magnitude(by_item,"Agreement",ROI=2)
PredictedRT_df <- Predicting_RT_with_spillover_refactored(rt.data,"Agreement")
```