---
title: "Spillover Analysis"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(plyr)
library(dplyr)
library(tidyr)
library(lme4)
library(lmerTest)
library(stringr)
```

This document will fit the *filler model*, a linear mixed effects model mapping surprisals 0--3 words back (and several nuisance factors) to reading times over the filler items. This model will be used to convert surprisals to reading times in the analysis code in each subset's analysis code.



Load in SPR and surprisal data for a subset
```{r}
spr <- read.csv("./Fillers.csv")
spr$Sentence <- str_replace_all(spr$Sentence, "%2C", ",")
spr <- spr %>% filter(RT<=7000) %>% filter(RT>0) %>% rename(participant = MD5)

surps_lstm <- read.csv("../data/gulordava/items_filler.lstm.csv.scaled")
surps_gpt2 <- read.csv("../data/gpt2/items_filler.gpt2.csv.scaled")
surps_rnng <- read.csv("../data/rnng/items_filler.rnng.csv.scaled")
surps_lstm$word_pos = surps_lstm$word_pos + 1# adjust to 1-indexing
surps_gpt2$word_pos = surps_gpt2$word_pos + 1# adjust to 1-indexing
surps_rnng$word_pos = surps_rnng$word_pos + 1# adjust to 1-indexing

```


```{r}

bind_surps <- function(spr, surps) {
  merged <- merge(x=spr, y=surps,
                  by.x=c("Sentence", "WordPosition"), by.y=c("Sentence", "word_pos"), 
                  all.x=TRUE)
  
  merged$item <- merged$item.x
  merged$surprisal_s <- merged$sum_surprisal_s #change to mean if that's more appropriate
  
  with_lags <- merged %>% group_by_at(vars(item, participant)) %>%
                    mutate(RT_p1 = lag(RT), 
                           RT_p2 = lag(RT_p1), 
                           RT_p3 = lag(RT_p2),
                           length_p1_s = lag(length_s), 
                           length_p2_s = lag(length_p1_s),
                           length_p3_s = lag(length_p2_s),
                           logfreq_p1_s = lag(logfreq_s), 
                           logfreq_p2_s = lag(logfreq_p1_s),
                           logfreq_p3_s = lag(logfreq_p2_s),
                           surprisal_p1_s = lag(surprisal_s),
                           surprisal_p2_s = lag(surprisal_p1_s),
                           surprisal_p3_s = lag(surprisal_p2_s)
                  )
  
  with_lags$sent_length <- lapply(str_split(with_lags$Sentence, " "), length)
  
  dropped <- subset(with_lags, !is.na(surprisal_s) &
                                        !is.na(surprisal_p1_s) & 
                                        !is.na(surprisal_p2_s) &
                                        !is.na(surprisal_p3_s) &
                                        !is.na(logfreq_s) & !is.na(logfreq_p1_s) &
                                        !is.na(logfreq_p2_s) & !is.na(logfreq_p3_s) & 
                      (with_lags$sent_length != with_lags$WordPosition))
  
  print(paste0("dropped: ", nrow(with_lags) - nrow(dropped)))
  return(dropped)
}


```


```{r}

dropped.lstm <- bind_surps(spr, surps_lstm)

models.filler.lstm <- lmer(data=dropped.lstm,
                      RT ~ surprisal_s + surprisal_p1_s + surprisal_p2_s + surprisal_p3_s +
                           scale(WordPosition) + logfreq_s*length_s + logfreq_p1_s*length_p1_s + 
                           logfreq_p2_s*length_p2_s + logfreq_p3_s*length_p3_s + 
                        (1 + surprisal_s + surprisal_p1_s + surprisal_p2_s + surprisal_p3_s || participant) + (1 | item),
                      control=lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
summary(models.filler.lstm) 

saveRDS(models.filler.lstm, "filler_models/filler_lstm_sum.rds")

rm(dropped.lstm) # free memory
gc()
```

```{r}
dropped.gpt2 <- bind_surps(spr, surps_gpt2)

models.filler.gpt2 <- lmer(data=dropped.gpt2,
                      RT ~ surprisal_s + surprisal_p1_s + surprisal_p2_s + surprisal_p3_s +
                           scale(WordPosition) + logfreq_s*length_s + logfreq_p1_s*length_p1_s + 
                           logfreq_p2_s*length_p2_s + logfreq_p3_s*length_p3_s + 
                        (1 + surprisal_s + surprisal_p1_s + surprisal_p2_s + surprisal_p3_s || participant) + (1 | item),
                      control=lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
summary(models.filler.gpt2) 

saveRDS(models.filler.gpt2, "filler_models/filler_gpt2_sum.rds")

rm(dropped.gpt2) # free memory
gc()
```

```{r}
dropped.rnng <- bind_surps(spr, surps_rnng)

models.filler.rnng <- lmer(data=dropped.rnng,
                      RT ~ surprisal_s + surprisal_p1_s + surprisal_p2_s + surprisal_p3_s +
                           scale(WordPosition) + logfreq_s*length_s + logfreq_p1_s*length_p1_s + 
                           logfreq_p2_s*length_p2_s + logfreq_p3_s*length_p3_s + 
                        (1 + surprisal_s + surprisal_p1_s + surprisal_p2_s + surprisal_p3_s || participant) + (1 | item),
                      control=lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
summary(models.filler.rnng) 

saveRDS(models.filler.rnng, "filler_models/filler_rnng_sum.rds")

rm(dropped.rnng) # free memory
gc()
```
