---
title: "Plots for SAP Benchmark"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(brms)
library(bayestestR)
library(tidytext)
library(tidyr)
library(dplyr)
```



## Load in relevant data

#### BRMS models

```{r}
subsets <- c('ClassicGP', 'RelativeClause', 'AttachmentAmbiguity','Agreement')
by_item <-list()
by_construction <-list()
i <- 1
for(s in subsets){
  print(s)
  curr_item <- readRDS(paste0('./', s, '/by_item.rds')) %>%
    mutate(ROI = as.character(ROI)) %>%
    select(item, ROI, coef, mean, lower, upper)  #make sure everything has same order
  curr_item_gpt2 <- readRDS(paste0('./', s, '/by_item_gpt2.rds')) %>%
    mutate(ROI = as.character(ROI)) %>%
    select(item, ROI, coef, mean) %>%
    rename(mean_gpt2 = mean)
  curr_item <- merge(curr_item, curr_item_gpt2, by=c('item', 'ROI', 'coef'), all.x = TRUE)
  curr_item_lstm <- readRDS(paste0('./', s, '/by_item_lstm.rds')) %>%
    mutate(ROI = as.character(ROI)) %>%
    select(item, ROI, coef, mean) %>%
    rename(mean_lstm = mean)
  curr_item <- merge(curr_item, curr_item_lstm, by=c('item', 'ROI', 'coef'), all.x = TRUE)
  curr_item_nosurp <- readRDS(paste0('./', s, '/by_item_nosurp.rds')) %>%
    mutate(ROI = as.character(ROI)) %>%
    select(item, ROI, coef, mean) %>%
    rename(mean_nosurp = mean)
  curr_item <- merge(curr_item, curr_item_nosurp, by=c('item', 'ROI', 'coef'), all.x = TRUE)
  by_item[[i]] <- curr_item
  
  ## By construction
  
  curr_construction <- readRDS(paste0('./', s, '/by_construction.rds')) %>%
    mutate(ROI = as.character(ROI),
    type = 'Empirical') %>%
    select(ROI, coef, mean, lower, upper, type)  #make sure everything has same order
  curr_construction_gpt2 <- readRDS(paste0('./', s, '/by_construction_gpt2.rds'))%>%
    mutate(ROI = as.character(ROI),
    type = 'GPT2') %>%
    select(ROI, coef, mean, lower, upper, type)
  curr_construction <- dplyr::bind_rows(curr_construction, curr_construction_gpt2)
  curr_construction_lstm <- readRDS(paste0('./', s, '/by_construction_lstm.rds')) %>%
    mutate(ROI = as.character(ROI),
    type = 'LSTM') %>%
    select(ROI, coef, mean, lower, upper, type)
  curr_construction <- dplyr::bind_rows(curr_construction, curr_construction_lstm)
  curr_construction_nosurp <- readRDS(paste0('./', s, '/by_construction_nosurp.rds')) %>%
    mutate(ROI = as.character(ROI),
    type = 'nosurp') %>%
    select(ROI, coef, mean, lower, upper, type)
  curr_construction <- dplyr::bind_rows(curr_construction, curr_construction_nosurp)
  by_construction[[i]] <- curr_construction
  i <- i+1
}
by_item <- dplyr::bind_rows(by_item)
by_construction <- dplyr::bind_rows(by_construction)
```



## Plot 1: By item variance across EOIs

```{r}
by_item_ROI_summ <- by_item %>%
  group_by(ROI, coef) %>%
  summarise(mean = mean(mean)) %>%
  ungroup() %>%
  group_by(coef) %>%
  mutate(max = max(mean),
         max_ROI = ifelse(max == mean, TRUE, FALSE)) %>%
  select(ROI, coef, max_ROI)
x <- by_item_ROI_summ %>%
  filter(max_ROI)
  
  
by_item <- merge(by_item, by_item_ROI_summ, by=c('ROI', 'coef')) %>%
  group_by(coef, ROI) %>%
  mutate(item = reorder_within(item, mean, coef),
         rank = rank(mean),
         greater_than_zero = ifelse(lower > 0, TRUE, FALSE),
         coef = factor(coef, levels = c('GPE_NPS', 'GPE_MVRR', 'GPE_NPZ', 'GPE','Agr', 'GPE_low', 'GPE_high', 'RC')))


#for RC, ROI==2 (noun) is critical +1 region
by_item$max_ROI <- ifelse(by_item$coef=="RC"&by_item$ROI==2,TRUE,
                          ifelse(by_item$coef=="RC"&by_item$ROI==0,FALSE,by_item$max_ROI))
#for GPE_low, ROI==1 is critical +1 region
by_item$max_ROI <- ifelse(by_item$coef=="GPE_low"&by_item$ROI==1,TRUE,
                          ifelse(by_item$coef=="GPE_low"&by_item$ROI==0,FALSE,by_item$max_ROI))

```


```{r}
by_item$EOI <- factor(by_item$coef,levels=c("GPE_MVRR","GPE_NPS","GPE_NPZ","RC","GPE_high","GPE_low","Agr"),labels=c("MV/RRC","DO/Sent","T/I","RC","HIGH","LOW","AGREE"))
by_construction$EOI <- factor(by_construction$coef,levels=c("GPE_MVRR","GPE_NPS","GPE_NPZ","RC","GPE_high","GPE_low","Agr"),labels=c("MV/RRC","DO/Sent","T/I","RC","HIGH","LOW","AGREE"))
EOI.labs <- c("MV/RRC"="Main verb / reduced relative clause","DO/Sent"="Direct object / sentential complement","T/I"="Transitive / intransitive","RC"="Subject / object relative clause","HIGH"="High attachment","LOW"="Low attachment","AGREE"="Subject-verb agreement mismatch")
CoV_labels <- data.frame(EOI=c("MV/RRC","DO/Sent","T/I","RC","HIGH","LOW","AGREE"),label = c("CoV=.181", "CoV=.610", "CoV=.368","CoV=.1.92","CoV=.343","CoV=1.86","CoV=.177"))
ggplot(by_item %>%
         filter(max_ROI),
       aes(x = rank, y = mean, alpha = greater_than_zero)) + 
  geom_point(size=3)+
  geom_errorbar(aes(ymin=lower,
                    ymax=upper),
                width=0.7,size=1.2) +
  facet_wrap(~EOI, nrow=2, labeller=labeller(EOI=EOI.labs))  + 
  geom_hline(yintercept=0, linetype = 'dashed')+
  scale_alpha_manual(values=c(0.25, 1)) + theme_hc()+
  theme(
      axis.text.x = element_blank(),
         axis.ticks.x = element_blank(),
        legend.position = 'none',
      strip.text.x = element_text(size = 15), axis.title.y = element_text(size=18,face="bold"),
      axis.title.x = element_text(size=18,face="bold"),
      axis.text.y=element_text(size=15)) + 
  labs(x = 'Item (sorted by effect magnitude)', y = 'Posterior estimate of magnitude of effect of interest (ms)')
# ggsave('./pdfs/by-item-all-eoi.pdf', width=15,height=7)
#empirical coefficients of variation
sd(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean)/by_construction[by_construction$ROI==1&by_construction$EOI=="MV/RRC"&by_construction$type=="Empirical",]$mean
sd(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean)/by_construction[by_construction$ROI==1&by_construction$EOI=="DO/Sent"&by_construction$type=="Empirical",]$mean
sd(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean)/by_construction[by_construction$ROI==1&by_construction$EOI=="T/I"&by_construction$type=="Empirical",]$mean
sd(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean)/by_construction[by_construction$ROI==2&by_construction$EOI=="RC"&by_construction$type=="Empirical",]$mean
sd(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean)/by_construction[by_construction$ROI==1&by_construction$EOI=="HIGH"&by_construction$type=="Empirical",]$mean
sd(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean)/by_construction[by_construction$ROI==1&by_construction$EOI=="LOW"&by_construction$type=="Empirical",]$mean
sd(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean)/by_construction[by_construction$ROI==1&by_construction$EOI=="AGREE"&by_construction$type=="Empirical",]$mean
```


## Plot 2: Construction level effects

```{r}
by_const_maxROIs <- by_construction %>%
  filter(type == 'Empirical') %>%
  group_by(coef) %>%
  mutate(max = max(mean),
         max_ROI = ifelse(max == mean, TRUE, FALSE)) %>%
  ungroup() %>%
  select(coef, ROI, max_ROI)
by_construction <- merge(by_construction, by_const_maxROIs, by = c('coef', 'ROI')) %>%
         mutate(EOI = factor(coef, levels = c('GPE_MVRR', 'GPE_NPS', 'GPE_NPZ', 'RC', 'GPE_high', 'GPE_low','Agr'),labels=c("Main verb /\n reduced relative clause","Direct object /\n sentential complement","Transitive / intransitive","Subject / object \nrelative clause","High attachment","Low attachment","Subject-verb\n agreement mismatch")))

#for RC, ROI==2 (noun) is critical +1 region
by_construction$max_ROI <- ifelse(by_construction$coef=="RC"&by_construction$ROI==2,TRUE,
                          ifelse(by_construction$coef=="RC"&by_construction$ROI==0,FALSE,by_construction$max_ROI))
#for GPE_low, ROI==1 is critical +1 region
by_construction$max_ROI <- ifelse(by_construction$coef=="GPE_low"&by_construction$ROI==1,TRUE,
                          ifelse(by_construction$coef=="GPE_low"&by_construction$ROI==0,FALSE,by_construction$max_ROI))


by_construction$type <- factor(by_construction$type,levels=c("nosurp","LSTM","GPT2","Empirical"),labels=c("No surprisal baseline","Wiki-LSTM","GPT-2","Empirical"))
ggplot(by_construction %>%
         filter(max_ROI), aes(x=EOI, y=mean, color=type))+
  geom_point(size=2.5,position = position_dodge(width=1))+ylab("Posterior estimate of empirical/predicted magnitude\n of effect of interest (ms)")+
  geom_errorbar(aes(ymin=lower,
                     ymax=upper),
                 position = position_dodge(width = 1),
                 width = 0.2,size=1)+xlab("Effect of interest")+
  scale_color_manual(labels = c('No surprisal baseline','Wiki-LSTM','GPT-2','Empirical'),values = c("#FFC107","#1E88E5","#D81B60","#004D40"))+
  scale_x_discrete(labels=c("Main verb /\n reduced relative clause","Direct object /\n sentential complement","Transitive /\n intransitive","Subject / object \nrelative clause","High attachment","Low attachment","Subject-verb\n agreement mismatch","Filler"))+ theme_minimal()+theme(legend.position="top", legend.box = "horizontal",legend.text = element_text(size=15), legend.title = element_text(size=18,face="bold"),
  axis.title.y = element_text(size=18,face="bold"),
      axis.title.x = element_text(size=18,face="bold"),
      axis.text.y=element_text(size=15),
  axis.text.x=element_text(size=15, angle = 20))+
    geom_hline(yintercept = 0, linetype='dashed')
# ggsave('./pdfs/by-construction-emp-surp.pdf', width=15,height=7)
```



```{r, fig.width=9.25, fig.height=9.25}
# LSTM
lstm_GP_EOI_MV <- ggplot(by_item %>% filter(EOI == "MV/RRC" && ROI==1), aes(x=mean_lstm, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
lstm_GP_EOI_DO <- ggplot(by_item %>% filter(EOI == "DO/Sent" && ROI==1), aes(x=mean_lstm, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
lstm_GP_EOI_TI <- ggplot(by_item %>% filter(EOI == "T/I" && ROI==1), aes(x=mean_lstm, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
lstm_RC_EOI <- ggplot(by_item %>% filter(EOI=="RC" && ROI==2), aes(x=mean_lstm, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
lstm_AA_EOI_HIGH <- ggplot(by_item %>% filter(EOI=="HIGH" && ROI==1), aes(x=mean_lstm, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs))+
  theme_fivethirtyeight()
lstm_AA_EOI_LOW <- ggplot(by_item %>% filter(EOI=="LOW" && ROI==1), aes(x=mean_lstm, y=mean)) +
  geom_point()+
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs))+
  theme_fivethirtyeight()
lstm_Agr_EOI <- ggplot(by_item %>% filter(EOI=="AGREE" && ROI==1), aes(x=mean_lstm, y=mean)) + 
  geom_point() + 
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
lstm_arr<- ggarrange(lstm_GP_EOI_MV, lstm_GP_EOI_DO, lstm_GP_EOI_TI, lstm_AA_EOI_HIGH, lstm_AA_EOI_LOW, lstm_RC_EOI, lstm_Agr_EOI)
                    
annotate_figure(lstm_arr, bottom=text_grob("Predicted EOI", color="#3C3C3C", size=12, family="sans"), left=text_grob("Empirical EOI" , color="#3C3C3C", size=12, family="sans", rot=90))+theme_fivethirtyeight()
# GPT2
gpt_GP_EOI_MV <- ggplot(by_item %>% filter(EOI == "MV/RRC" && ROI==1), aes(x=mean_gpt2, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
gpt_GP_EOI_DO <- ggplot(by_item %>% filter(EOI == "DO/Sent" && ROI==1), aes(x=mean_gpt2, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
gpt_GP_EOI_TI <- ggplot(by_item %>% filter(EOI == "T/I" && ROI==1), aes(x=mean_gpt2, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
gpt_RC_EOI <- ggplot(by_item %>% filter(EOI=="RC" && ROI==2), aes(x=mean_gpt2, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
gpt_AA_EOI_HIGH <- ggplot(by_item %>% filter(EOI=="HIGH" && ROI==1), aes(x=mean_gpt2, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs))+
  theme_fivethirtyeight()
gpt_AA_EOI_LOW <- ggplot(by_item %>% filter(EOI=="LOW" && ROI==1), aes(x=mean_gpt2, y=mean)) +
  geom_point()+
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs))+
  theme_fivethirtyeight()
gpt_Agr_EOI <- ggplot(by_item %>% filter(EOI=="AGREE" && ROI==1), aes(x=mean_gpt2, y=mean)) + 
  geom_point() + 
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
gpt_arr<- ggarrange(gpt_GP_EOI_MV, gpt_GP_EOI_DO, gpt_GP_EOI_TI, gpt_AA_EOI_HIGH, gpt_AA_EOI_LOW, gpt_RC_EOI, gpt_Agr_EOI)
                    
annotate_figure(gpt_arr, bottom=text_grob("Predicted EOI", color="#3C3C3C", size=12, family="sans"), left=text_grob("Empirical EOI" , color="#3C3C3C", size=12, family="sans", rot=90))+theme_fivethirtyeight()
# BASELINE
nosurp_GP_EOI_MV <- ggplot(by_item %>% filter(EOI == "MV/RRC" && ROI==1), aes(x=mean_nosurp, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
nosurp_GP_EOI_DO <- ggplot(by_item %>% filter(EOI == "DO/Sent" && ROI==1), aes(x=mean_nosurp, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
nosurp_GP_EOI_TI <- ggplot(by_item %>% filter(EOI == "T/I" && ROI==1), aes(x=mean_nosurp, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
nosurp_RC_EOI <- ggplot(by_item %>% filter(EOI=="RC" && ROI==2), aes(x=mean_nosurp, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
nosurp_AA_EOI_HIGH <- ggplot(by_item %>% filter(EOI=="HIGH" && ROI==1), aes(x=mean_nosurp, y=mean)) +
  geom_point() +
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs))+
  theme_fivethirtyeight()
nosurp_AA_EOI_LOW <- ggplot(by_item %>% filter(EOI=="LOW" && ROI==1), aes(x=mean_nosurp, y=mean)) +
  geom_point()+
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs))+
  theme_fivethirtyeight()
nosurp_Agr_EOI <- ggplot(by_item %>% filter(EOI=="AGREE" && ROI==1), aes(x=mean_nosurp, y=mean)) + 
  geom_point() + 
  facet_wrap(~EOI, labeller=labeller(EOI=EOI.labs)) +
  theme_fivethirtyeight()
nosurp_arr<- ggarrange(nosurp_GP_EOI_MV, nosurp_GP_EOI_DO, nosurp_GP_EOI_TI, nosurp_AA_EOI_HIGH, nosurp_AA_EOI_LOW, nosurp_RC_EOI, nosurp_Agr_EOI)
                    
annotate_figure(nosurp_arr, bottom=text_grob("Predicted EOI", color="#3C3C3C", size=12, family="sans"), left=text_grob("Empirical EOI" , color="#3C3C3C", size=12, family="sans", rot=90))+theme_fivethirtyeight()
```


```{r}
noise.summary <- read.csv("noiseceiling_summary.csv") %>%
  gather("Effect","Correlation",2:9) %>%
  rename("EOI" = Effect,
         "Ceiling" = Correlation)
GP.data <- readRDS("correlation/sampled_correlations_maxregion_GP.rds")
RC.data <- readRDS("correlation/sampled_correlations_P2_RC.rds")
AA.data <- readRDS("correlation/sampled_correlations_P1_AA.rds")
Agr.data <- readRDS("correlation/sampled_correlations_maxregion_Agr.rds")
all.data <- rbind(GP.data,RC.data,AA.data,Agr.data) %>% left_join(noise.summary)
cor.summary <- all.data %>%
                group_by(EOI,model) %>%
                summarize(
                  mean = mean(Correlation),
                  ceiling = mean(Ceiling),
                  lower.25 = quantile(Correlation,.25),
                  lower.10 = quantile(Correlation,.10),
                  lower.025 = quantile(Correlation,.025),
                  upper.75 = quantile(Correlation,.75),
                  upper.90 = quantile(Correlation,.90),
                  upper.975 = quantile(Correlation,.975)
                ) %>%
                rename("Model" = model)
filler_results <- read.csv("correlation/3 models filler.csv",header=T)
filler_summary <- data.frame(EOI="Filler",Model=c("lstm","gpt2","nosurp"),mean=NA,ceiling=0.99,lower.25=NA,lower.10=NA,lower.025=NA,upper.75=NA,upper.90=NA,upper.975=NA)
for(i in 2:ncol(filler_results)){
  filler_summary[i-1,'mean'] <- mean(filler_results[,i])
  filler_summary[i-1,'lower.025'] <- mean(filler_results[,i])-1.96*sd(filler_results[,i])
  filler_summary[i-1,'upper.975'] <- mean(filler_results[,i])+1.96*sd(filler_results[,i])
  filler_summary[i-1,'lower.10'] <- mean(filler_results[,i])-1.283*sd(filler_results[,i])
  filler_summary[i-1,'upper.90'] <- mean(filler_results[,i])+1.283*sd(filler_results[,i])
  filler_summary[i-1,'lower.25'] <- mean(filler_results[,i])-0.675*sd(filler_results[,i])
  filler_summary[i-1,'upper.75'] <- mean(filler_results[,i])+0.675*sd(filler_results[,i])
}
cor.summary <- rbind(cor.summary,filler_summary)
cor.summary$EOI <- factor(cor.summary$EOI, levels = c("GPE_MVRR","GPE_NPS","GPE_NPZ","RC","GPE_high","GPE_low","Agr","Filler") )
cor.summary$Model <- factor(cor.summary$Model,levels = c("nosurp","lstm","gpt2"))
cor.summary <- cor.summary[!is.na(cor.summary$Model),]
ggplot(cor.summary, aes(x=EOI, y=mean, color=Model))+
  geom_rect(inherit.aes=FALSE,
            aes(xmin=as.numeric(EOI)-.25,xmax=as.numeric(EOI)+0.25,ymin=0,ymax=ceiling), alpha=0.1)+
  geom_linerange(aes(ymin=lower.025,ymax=upper.975),lwd=0.5,position = position_dodge(width=.5))+
  geom_linerange(aes(ymin=lower.25,ymax=upper.75),lwd=1.75,position = position_dodge(width=.5))+
  geom_point(lwd=4,position = position_dodge(width=.5))+
  ylim(-.45,1)+ylab("Correlation between model predictions and data")+xlab("Effect of Interest")+
  scale_color_manual(labels = c('No surprisal baseline','Wiki-LSTM','GPT-2'),values = c("#FFC107","#1E88E5","#D81B60"))+
  scale_x_discrete(labels=c("Main verb /\n reduced relative clause","Direct object /\n sentential complement","Transitive /\n intransitive","Subject / object \nrelative clause","High attachment","Low attachment","Subject-verb\n agreement mismatch","Filler"))+ theme_minimal()+theme(legend.position="top", legend.box = "horizontal",legend.text = element_text(size=15), legend.title = element_text(size=18,face="bold"),
  axis.title.y = element_text(size=18,face="bold"),
      axis.title.x = element_text(size=18,face="bold"),
      axis.text.y=element_text(size=15),
  axis.text.x=element_text(size=15, angle = 20, hjust = 0.8))+
  geom_text(x=1.4, y=1, size=5, family = 'sans',inherit.aes = FALSE, label="Maximal explainable variance")+
  geom_segment(inherit.aes = FALSE, x = 1, y = 0.98, xend = 1, yend = .82, arrow = arrow(length = unit(0.2,"cm")))
# ggsave('./pdfs/by-item-emp-pred-cor.pdf', width=15,height=7)
```


```{r}
by_construction_empirical <- by_construction[by_construction$type=="Empirical",]
by_construction_empirical$ROI <- ifelse(by_construction_empirical$coef=="RC"&by_construction_empirical$ROI==0,2,ifelse(by_construction_empirical$coef=="RC"&by_construction_empirical$ROI==1,0,ifelse(by_construction_empirical$coef=="RC"&by_construction_empirical$ROI==2,1,by_construction_empirical$ROI)))
by_construction_empirical$ROI <- factor(by_construction_empirical$ROI,levels=c(0,1,2),labels=c("Critical","Critical+1","Critical+2"))
ggplot(by_construction_empirical, aes(x=EOI, y=mean,fill=ROI))+
  geom_bar(stat="identity",position = position_dodge(width=1))+
  scale_fill_manual(values = c("royalblue3","tan2","forestgreen"))+ylab("Empirical effect size (ms)")+
  geom_errorbar(aes(ymin=lower,
                     ymax=upper),
                 position = position_dodge(width = 1),
                 width = 0.2,size=1)+xlab("Effect of interest")+
  scale_x_discrete(labels=c("Main verb /\n reduced relative clause","Direct object /\n sentential complement","Transitive /\n intransitive","Subject / object \nrelative clause","High attachment","Low attachment","Subject-verb\n agreement mismatch","Filler"))+theme(legend.position="top", legend.box = "horizontal",legend.text = element_text(size=15), legend.title = element_text(size=18,face="bold"),
  axis.title.y = element_text(size=18,face="bold"),
      axis.title.x = element_text(size=18,face="bold"),
      axis.text.y=element_text(size=15),
  axis.text.x=element_text(size=15, angle = 20))+
    geom_hline(yintercept = 0, linetype='dashed')
#ggsave('./pdfs/SI_EOI_ROI.pdf', width=15,height=7)
```



```{r EOI and baseline absolute RT, fig.width=8.25, fig.height=8.25}
ratio_display = 1
GP_by_item <- cbind(readRDS("ClassicGP/by_item.rds"),
                  unamb_mean=readRDS("ClassicGP/by_item_unamb.rds")[,4])
GP_by_item$EOI <- factor(GP_by_item$coef,levels=c("GPE_MVRR","GPE_NPS","GPE_NPZ"),labels=c("Main verb / reduced relative clause","Direct object / sentential complement","Transitive / intransitive"))
GP_by_item$ROI <- factor(GP_by_item$ROI,levels=c(0, 1, 2),labels=c("critical","critical + 1","critical + 2"))
baselinevsEOI_GP <- GP_by_item %>% group_by(ROI,EOI) %>% do(CORR=cor.test(.$mean,.$unamb_mean))
ratio_GP_by_item = (max(GP_by_item$unamb_mean)-min(GP_by_item$unamb_mean))/(max(GP_by_item$mean)-min(GP_by_item$mean))
gp_corr <- baselinevsEOI_GP %>%
  mutate(paste("r=",toString(round(CORR[[4]][[1]],2)), sep="")) %>%
  rename(est = `paste("r=", toString(round(CORR[[4]][[1]], 2)), sep = "")`)
ggplot(GP_by_item,aes(x=unamb_mean,y=mean))+
  facet_wrap(ROI~EOI)+
  geom_point()+
  geom_smooth(method="lm",formula=y~x)+
  labs(y="Classic garden path effect",x="Mean RT in the unambiguous sentence (ms)")+
  theme_fivethirtyeight()+
  theme(axis.title = element_text())+
  coord_fixed(ratio=(ratio_GP_by_item / ratio_display))+
  facet_grid(ROI~EOI) +
  geom_label(
    size    = 4,
    data    = gp_corr,
    mapping = aes(x = Inf, y = Inf, label=est),
    hjust   = 1.05,
    vjust   = 1.05,
    color   ="#3C3C3C",
    family  = "sans",
  )
for(i in 1:nrow(baselinevsEOI_GP)){
  print(c(baselinevsEOI_GP[i,'ROI'][[1]],as.character(baselinevsEOI_GP[i,'EOI'][[1]]),round(baselinevsEOI_GP[i,'CORR'][[1]][[1]]$estimate,3)))
}
RC_by_item <- cbind(readRDS("RelativeClause/by_item.rds"),
                    SRC_mean=readRDS("RelativeClause/by_item_SRC.rds")[,4])
RC_by_item$EOI <- factor(RC_by_item$coef,levels=c("RC"),labels=c("Subject / object relative clause"))
RC_by_item$ROI <- factor(RC_by_item$ROI,levels=c(0, 1, 2),labels=c("critical","critical + 1","critical + 2"))
baselinevsEOI_RC <- RC_by_item %>% group_by(ROI,EOI) %>% do(CORR=cor.test(.$mean,.$SRC_mean))
ratio_RC_by_item = (max(RC_by_item$SRC_mean)-min(RC_by_item$SRC_mean))/(max(RC_by_item$mean)-min(RC_by_item$mean))
rc_corr <- baselinevsEOI_RC %>%
  mutate(paste("r=",toString(round(CORR[[4]][[1]],2)), sep="")) %>%
  rename(est = `paste("r=", toString(round(CORR[[4]][[1]], 2)), sep = "")`)
ggplot(RC_by_item,aes(x=SRC_mean,y=mean))+
  facet_wrap(ROI~EOI,nrow=3)+
  geom_point()+
  geom_smooth(method="lm",formula=y~x)+
  labs(y="Object over subject relative clause difficulty",x="Mean RT in subject relative clauses (ms)")+
  theme_fivethirtyeight()+
  theme(axis.title = element_text())+
  coord_fixed(ratio=(ratio_RC_by_item / ratio_display))+
  facet_grid(ROI~EOI) +
  geom_label(
    size    = 4,
    data    = rc_corr,
    mapping = aes(x = Inf, y = Inf, label=est),
    hjust   = 1.05,
    vjust   = 1.05,
    color   ="#3C3C3C",
    family  = "sans",
  )
for(i in 1:nrow(baselinevsEOI_RC)){
  print(c(baselinevsEOI_RC[i,'ROI'][[1]],as.character(baselinevsEOI_RC[i,'EOI'][[1]]),round(baselinevsEOI_RC[i,'CORR'][[1]][[1]]$estimate,3)))
}
AA_by_item <- cbind(readRDS("AttachmentAmbiguity/by_item.rds"),
                    multi_mean=readRDS("AttachmentAmbiguity/by_item_multi.rds")[,4])
AA_by_item$EOI <- factor(AA_by_item$coef,levels=c("GPE_high","GPE_low"),labels=c("High attachment","Low attachment"))
AA_by_item$ROI <- factor(AA_by_item$ROI,levels=c(0, 1, 2),labels=c("critical","critical + 1","critical + 2"))
baselinevsEOI_AA <- AA_by_item %>% group_by(ROI,EOI) %>% do(CORR=cor.test(.$mean,.$multi_mean))
ratio_AA_by_item = (max(AA_by_item$multi_mean)-min(AA_by_item$multi_mean))/(max(AA_by_item$mean)-min(AA_by_item$mean))
aa_corr <- baselinevsEOI_AA %>%
  mutate(paste("r=",toString(round(CORR[[4]][[1]],2)), sep="")) %>%
  rename(est = `paste("r=", toString(round(CORR[[4]][[1]], 2)), sep = "")`)
ggplot(AA_by_item,aes(x=multi_mean,y=mean))+
  facet_wrap(ROI~EOI,nrow=3)+
  geom_point()+
  geom_smooth(method="lm",formula=y~x)+
  labs(y="Attachment ambiguity effect",x="Mean RT in sentence with ambiguous attachment (ms)")+
  theme_fivethirtyeight()+
  theme(axis.title = element_text())+
  coord_fixed(ratio=(ratio_AA_by_item / ratio_display))+
  facet_grid(ROI~EOI) +
  geom_label(
    size    = 4,
    data    = aa_corr,
    mapping = aes(x = Inf, y = Inf, label=est),
    hjust   = 1.05,
    vjust   = 1.05,
    color   ="#3C3C3C",
    family  = "sans",
  )
for(i in 1:nrow(baselinevsEOI_AA)){
  print(c(baselinevsEOI_AA[i,'ROI'][[1]],as.character(baselinevsEOI_AA[i,'EOI'][[1]]),round(baselinevsEOI_AA[i,'CORR'][[1]][[1]]$estimate,3)))
}
Agr_by_item <- cbind(readRDS("Agreement/by_item.rds"),
                    Agreed_mean=readRDS("Agreement/by_item_Agreed.rds")[,4])
Agr_by_item$EOI <- factor(Agr_by_item$coef,levels=c("Agr"),labels=c("Subject-verb agreement mismatch"))
Agr_by_item$ROI <- factor(Agr_by_item$ROI,levels=c(0, 1, 2),labels=c("critical","critical + 1","critical + 2"))
baselinevsEOI_Agr <- Agr_by_item %>% group_by(ROI,EOI) %>% do(CORR=cor.test(.$mean,.$Agreed_mean))
ratio_Agr_by_item = (max(Agr_by_item$Agreed_mean)-min(Agr_by_item$Agreed_mean))/(max(Agr_by_item$mean)-min(Agr_by_item$mean))
agr_corr <- baselinevsEOI_Agr %>%
  mutate(paste("r=",toString(round(CORR[[4]][[1]],2)), sep="")) %>%
  rename(est = `paste("r=", toString(round(CORR[[4]][[1]], 2)), sep = "")`)
ggplot(Agr_by_item,aes(x=Agreed_mean,y=mean))+
  facet_wrap(ROI~EOI,nrow=3)+
  geom_point()+
  geom_smooth(method="lm",formula=y~x)+
  labs(y="Agreement mismatch effect",x="Mean RT in the grammatical sentence (ms)")+
  theme_fivethirtyeight()+
  theme(axis.title = element_text())+
  coord_fixed(ratio=(ratio_Agr_by_item / ratio_display))+
  facet_grid(ROI~EOI) +
  geom_label(
    size    = 4,
    data    = agr_corr,
    mapping = aes(x = Inf, y = Inf, label=est, family='sans'),
    hjust   = 1.05,
    vjust   = 1.05,
    color   ="#3C3C3C",
    family  = "sans",
  )
for(i in 1:nrow(baselinevsEOI_Agr)){
  print(c(baselinevsEOI_Agr[i,'ROI'][[1]],as.character(baselinevsEOI_Agr[i,'EOI'][[1]]),round(baselinevsEOI_Agr[i,'CORR'][[1]][[1]]$estimate,3)))
}
```