---
title: "Plots for SAP Benchmark"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(brms)
library(bayestestR)
library(tidytext)
library(tidyr)
library(dplyr)
```



## Load in relevant data

#### BRMS models

```{r}
subsets <- c('ClassicGP', 'RelativeClause', 'AttachmentAmbiguity','Agreement')
by_item <-list()
by_construction <-list()
i <- 1
for(s in subsets){
  print(s)
  curr_item <- readRDS(paste0('./', s, '/by_item_log.rds')) %>%
    mutate(ROI = as.character(ROI)) %>%
    select(item, ROI, coef, mean, lower, upper)  #make sure everything has same order
  curr_item_gpt2 <- readRDS(paste0('./', s, '/by_item_gpt2_logadd.rds')) %>%
    mutate(ROI = as.character(ROI)) %>%
    select(item, ROI, coef, mean) %>%
    rename(mean_gpt2 = mean)
  curr_item <- merge(curr_item, curr_item_gpt2, by=c('item', 'ROI', 'coef'), all.x = TRUE)
  curr_item_lstm <- readRDS(paste0('./', s, '/by_item_lstm_logadd.rds')) %>%
    mutate(ROI = as.character(ROI)) %>%
    select(item, ROI, coef, mean) %>%
    rename(mean_lstm = mean)
  curr_item <- merge(curr_item, curr_item_lstm, by=c('item', 'ROI', 'coef'), all.x = TRUE)
  curr_item_nosurp <- readRDS(paste0('./', s, '/by_item_nosurp_logadd.rds')) %>%
    mutate(ROI = as.character(ROI)) %>%
    select(item, ROI, coef, mean) %>%
    rename(mean_nosurp = mean)
  curr_item <- merge(curr_item, curr_item_nosurp, by=c('item', 'ROI', 'coef'), all.x = TRUE)
  by_item[[i]] <- curr_item
  
  ## By construction
  
  curr_construction <- readRDS(paste0('./', s, '/by_construction_log.rds')) %>%
    mutate(ROI = as.character(ROI),
    type = 'Empirical') %>%
    select(ROI, coef, mean, lower, upper, type)  #make sure everything has same order
  curr_construction_gpt2 <- readRDS(paste0('./', s, '/by_construction_gpt2_logadd.rds'))%>%
    mutate(ROI = as.character(ROI),
    type = 'GPT2') %>%
    select(ROI, coef, mean, lower, upper, type)
  curr_construction <- dplyr::bind_rows(curr_construction, curr_construction_gpt2)
  curr_construction_lstm <- readRDS(paste0('./', s, '/by_construction_lstm_logadd.rds')) %>%
    mutate(ROI = as.character(ROI),
    type = 'LSTM') %>%
    select(ROI, coef, mean, lower, upper, type)
  curr_construction <- dplyr::bind_rows(curr_construction, curr_construction_lstm)
  curr_construction_nosurp <- readRDS(paste0('./', s, '/by_construction_nosurp_logadd.rds')) %>%
    mutate(ROI = as.character(ROI),
    type = 'nosurp') %>%
    select(ROI, coef, mean, lower, upper, type)
  curr_construction <- dplyr::bind_rows(curr_construction, curr_construction_nosurp)
  by_construction[[i]] <- curr_construction
  i <- i+1
}
by_item <- dplyr::bind_rows(by_item)
by_construction <- dplyr::bind_rows(by_construction)
```



## Plot 1: By item variance across EOIs

```{r}
by_item_ROI_summ <- by_item %>%
  group_by(ROI, coef) %>%
  summarise(mean = mean(mean)) %>%
  ungroup() %>%
  group_by(coef) %>%
  mutate(max = max(mean),
         max_ROI = ifelse(max == mean, TRUE, FALSE)) %>%
  select(ROI, coef, max_ROI)
x <- by_item_ROI_summ %>%
  filter(max_ROI)
  
  
by_item <- merge(by_item, by_item_ROI_summ, by=c('ROI', 'coef')) %>%
  group_by(coef, ROI) %>%
  mutate(item = reorder_within(item, mean, coef),
         rank = rank(mean),
         greater_than_zero = ifelse(lower > 0, TRUE, FALSE),
         coef = factor(coef, levels = c('GPE_NPS', 'GPE_MVRR', 'GPE_NPZ', 'GPE','Agr', 'GPE_low', 'GPE_high', 'RC')))


#for RC, ROI==2 (noun) is critical +1 region
by_item$max_ROI <- ifelse(by_item$coef=="RC"&by_item$ROI==2,TRUE,
                          ifelse(by_item$coef=="RC"&by_item$ROI==0,FALSE,by_item$max_ROI))
#for GPE_low, ROI==1 is critical +1 region
by_item$max_ROI <- ifelse(by_item$coef=="GPE_low"&by_item$ROI==1,TRUE,
                          ifelse(by_item$coef=="GPE_low"&by_item$ROI==0,FALSE,by_item$max_ROI))

```


```{r}
by_item$EOI <- factor(by_item$coef,levels=c("GPE_MVRR","GPE_NPS","GPE_NPZ","RC","GPE_high","GPE_low","Agr"),labels=c("MV/RRC","DO/Sent","T/I","RC","HIGH","LOW","AGREE"))
by_construction$EOI <- factor(by_construction$coef,levels=c("GPE_MVRR","GPE_NPS","GPE_NPZ","RC","GPE_high","GPE_low","Agr"),labels=c("MV/RRC","DO/Sent","T/I","RC","HIGH","LOW","AGREE"))
EOI.labs <- c("MV/RRC"="Main verb / reduced relative","DO/Sent"="Direct object / sentential complement","T/I"="Transitive / intransitive","RC"="Object vs. subject relative clause","HIGH"="High attachment","LOW"="Low attachment","AGREE"="Agreement violation")
CoV_labels <- data.frame(EOI=c("MV/RRC","DO/Sent","T/I","RC","HIGH","LOW","AGREE"),label = c("CoV=.181", "CoV=.610", "CoV=.368","CoV=.1.92","CoV=.343","CoV=1.86","CoV=.177"))
ggplot(by_item %>%
         filter(max_ROI),
       aes(x = rank, y = mean, alpha = greater_than_zero)) + 
  geom_point(size=3)+
  geom_errorbar(aes(ymin=lower,
                    ymax=upper),
                width=0.7,size=1.2) +
  facet_wrap(~EOI, nrow=2, labeller=labeller(EOI=EOI.labs))  + 
  geom_hline(yintercept=0, linetype = 'dashed')+
  scale_alpha_manual(values=c(0.25, 1)) + theme_hc()+
  theme(
      axis.text.x = element_blank(),
         axis.ticks.x = element_blank(),
        legend.position = 'none',
      strip.text.x = element_text(size = 15), axis.title.y = element_text(size=18,face="bold"),
      axis.title.x = element_text(size=18,face="bold"),
      axis.text.y=element_text(size=15)) + 
  labs(x = 'Item (sorted by effect magnitude)', y = 'Posterior estimate of effect of interest (ms)')
ggsave('./pdfs/by-item-all-eoi.pdf', width=15,height=7)


#V_2 empirical
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean)^2))^(1/2)
#0.21
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean)^2))^(1/2)
#0.54
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean)^2))^(1/2)
#0.33
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean)^2))^(1/2)
#0.84
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean)^2))^(1/2)
#0.38
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean)^2))^(1/2)
#0.72
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean)^2))^(1/2)
#0.15


#V_2 lstm
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean_lstm)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean_lstm)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean_lstm)^2))^(1/2)
#0.26
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean_lstm)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean_lstm)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean_lstm)^2))^(1/2)
#0.37
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean_lstm)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean_lstm)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean_lstm)^2))^(1/2)
#0.33
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean_lstm)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean_lstm)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean_lstm)^2))^(1/2)
#0.61
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean_lstm)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean_lstm)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean_lstm)^2))^(1/2)
#0.60
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean_lstm)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean_lstm)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean_lstm)^2))^(1/2)
#0.82
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean_lstm)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean_lstm)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean_lstm)^2))^(1/2)
#0.25

##V_2 gpt2
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean_gpt2)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean_gpt2)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="MV/RRC",]$mean_gpt2)^2))^(1/2)
#0.69
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean_gpt2)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean_gpt2)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="DO/Sent",]$mean_gpt2)^2))^(1/2)
#0.60
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean_gpt2)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean_gpt2)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="T/I",]$mean_gpt2)^2))^(1/2)
#0.29
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean_gpt2)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean_gpt2)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="RC",]$mean_gpt2)^2))^(1/2)
#0.99
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean_gpt2)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean_gpt2)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="HIGH",]$mean_gpt2)^2))^(1/2)
#0.49
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean_gpt2)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean_gpt2)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="LOW",]$mean_gpt2)^2))^(1/2)
#0.67
(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean_gpt2)/(var(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean_gpt2)+mean(by_item[by_item$max_ROI==TRUE&by_item$EOI=="AGREE",]$mean_gpt2)^2))^(1/2)
#0.14


```


## Plot 2: Construction level effects

```{r}
by_const_maxROIs <- by_construction %>%
  filter(type == 'Empirical') %>%
  group_by(coef) %>%
  mutate(max = max(mean),
         max_ROI = ifelse(max == mean, TRUE, FALSE)) %>%
  ungroup() %>%
  select(coef, ROI, max_ROI)
by_construction <- merge(by_construction, by_const_maxROIs, by = c('coef', 'ROI')) %>%
         mutate(EOI = factor(coef, levels = c('GPE_MVRR', 'GPE_NPS', 'GPE_NPZ', 'RC', 'GPE_high', 'GPE_low','Agr'),labels=c("Main verb /\n reduced relative","Direct object /\n sentential complement","Transitive / intransitive","Object vs. subject \nrelative clause","High attachment","Low attachment","Agreement violation")))

#for RC, ROI==2 (noun) is critical +1 region
by_construction$max_ROI <- ifelse(by_construction$coef=="RC"&by_construction$ROI==2,TRUE,
                          ifelse(by_construction$coef=="RC"&by_construction$ROI==0,FALSE,by_construction$max_ROI))
#for GPE_low, ROI==1 is critical +1 region
by_construction$max_ROI <- ifelse(by_construction$coef=="GPE_low"&by_construction$ROI==1,TRUE,
                          ifelse(by_construction$coef=="GPE_low"&by_construction$ROI==0,FALSE,by_construction$max_ROI))


by_construction$type <- factor(by_construction$type,levels=c("nosurp","LSTM","GPT2","Empirical"),labels=c("No surprisal baseline","Wiki-LSTM","GPT-2","Empirical"))
ggplot(by_construction %>%
         filter(max_ROI), aes(x=EOI, y=mean, color=type))+
  ylim(-25,225)+
  geom_point(size=2.5,position = position_dodge(width=1))+ylab("Posterior estimate of \nempirical/predicted effect of interest (ms)")+
  geom_errorbar(aes(ymin=lower,
                     ymax=upper),
                 position = position_dodge(width = 1),
                 width = 0.2,size=1)+xlab("Effect of interest")+
  scale_color_manual(labels = c('No surprisal baseline','Wiki-LSTM','GPT-2','Empirical'),values = c("#FFC107","#1E88E5","#D81B60","#004D40"))+
  scale_x_discrete(labels=c("Main verb /\n reduced relative","Direct object /\n sentential complement","Transitive /\n intransitive","Object vs. subject \nrelative clause","Low attachment","Agreement violation","Filler"))+ theme_minimal()+theme(legend.position="top", legend.box = "horizontal",legend.text = element_text(size=15), legend.title = element_text(size=18,face="bold"),
  axis.title.y = element_text(size=18,face="bold"),
      axis.title.x = element_text(size=18,face="bold"),
      axis.text.y=element_text(size=15),
  axis.text.x=element_text(size=15, angle = 20))+
    geom_hline(yintercept = 0, linetype='dashed')
ggsave('./pdfs/by-construction-emp-surp.pdf', width=15,height=7)
```




```{r}
noise.summary <- read.csv("noiseceiling_summary.csv") %>%
  gather("Effect","Correlation",2:9) %>%
  rename("EOI" = Effect,
         "Ceiling" = Correlation)
GP.data <- readRDS("correlation/sampled_correlations_P1_GP.rds")
RC.data <- readRDS("correlation/sampled_correlations_P2_RC.rds")
AA.data <- readRDS("correlation/sampled_correlations_P1_AA.rds")
Agr.data <- readRDS("correlation/sampled_correlations_P1_Agr.rds")
all.data <- rbind(GP.data,RC.data,AA.data,Agr.data) %>% left_join(noise.summary)
cor.summary <- all.data %>%
                group_by(EOI,model) %>%
                summarize(
                  mean = mean(Correlation),
                  ceiling = mean(Ceiling),
                  lower.25 = quantile(Correlation,.25),
                  lower.10 = quantile(Correlation,.10),
                  lower.025 = quantile(Correlation,.025),
                  upper.75 = quantile(Correlation,.75),
                  upper.90 = quantile(Correlation,.90),
                  upper.975 = quantile(Correlation,.975)
                ) %>%
                rename("Model" = model)
filler_results <- read.csv("correlation/3 models filler.csv",header=T)
filler_summary <- data.frame(EOI="Filler",Model=c("lstm","gpt2","nosurp"),mean=NA,ceiling=0.99,lower.25=NA,lower.10=NA,lower.025=NA,upper.75=NA,upper.90=NA,upper.975=NA)
for(i in 2:ncol(filler_results)){
  filler_summary[i-1,'mean'] <- mean(filler_results[,i])
  filler_summary[i-1,'lower.025'] <- mean(filler_results[,i])-1.96*sd(filler_results[,i])
  filler_summary[i-1,'upper.975'] <- mean(filler_results[,i])+1.96*sd(filler_results[,i])
  filler_summary[i-1,'lower.10'] <- mean(filler_results[,i])-1.283*sd(filler_results[,i])
  filler_summary[i-1,'upper.90'] <- mean(filler_results[,i])+1.283*sd(filler_results[,i])
  filler_summary[i-1,'lower.25'] <- mean(filler_results[,i])-0.675*sd(filler_results[,i])
  filler_summary[i-1,'upper.75'] <- mean(filler_results[,i])+0.675*sd(filler_results[,i])
}
cor.summary <- rbind(cor.summary,filler_summary)
cor.summary$EOI <- factor(cor.summary$EOI, levels = c("GPE_MVRR","GPE_NPS","GPE_NPZ","RC","GPE_high","GPE_low","Agr","Filler") )
cor.summary$Model <- factor(cor.summary$Model,levels = c("nosurp","lstm","gpt2"))
cor.summary <- cor.summary[!is.na(cor.summary$Model),]
ggplot(cor.summary, aes(x=EOI, y=mean, color=Model))+
  geom_rect(inherit.aes=FALSE,
            aes(xmin=as.numeric(EOI)-.25,xmax=as.numeric(EOI)+0.25,ymin=0,ymax=ceiling), alpha=0.1)+
  geom_linerange(aes(ymin=lower.025,ymax=upper.975),lwd=0.5,position = position_dodge(width=.5))+
  geom_linerange(aes(ymin=lower.25,ymax=upper.75),lwd=1.75,position = position_dodge(width=.5))+
  geom_point(size=4,position = position_dodge(width=.5))+
  ylim(-.45,1)+ylab("Correlation between model predictions and data")+xlab("Effect of Interest")+
  scale_color_manual(labels = c('No surprisal baseline','Wiki-LSTM','GPT-2'),values = c("#FFC107","#1E88E5","#D81B60"))+
  scale_x_discrete(labels=c("Main verb /\n reduced relative","Direct object /\n sentential complement","Transitive /\n intransitive","Object vs. subject\nrelative clause", "High attachment" ,"Low attachment","Agreement violation","Filler"))+ theme_minimal()+theme(legend.position="top", legend.box = "horizontal",legend.text = element_text(size=15), legend.title = element_text(size=18,face="bold"),
  axis.title.y = element_text(size=18,face="bold"),
      axis.title.x = element_text(size=18,face="bold"),
      axis.text.y=element_text(size=15),
  axis.text.x=element_text(size=15, angle = 20, hjust = 0.8))+
  geom_text(x=1.4, y=1, size=5, family = 'sans',inherit.aes = FALSE, label="Maximal explainable variance")+
  geom_segment(inherit.aes = FALSE, x = 1, y = 0.98, xend = 1, yend = .88, arrow = arrow(length = unit(0.2,"cm")))
ggsave('./pdfs/by-item-emp-pred-cor.pdf', width=15,height=7)
```


```{r}
by_construction_empirical <- by_construction[by_construction$type=="Empirical",]
by_construction_empirical$ROI <- ifelse(by_construction_empirical$coef=="RC"&by_construction_empirical$ROI==0,2,ifelse(by_construction_empirical$coef=="RC"&by_construction_empirical$ROI==1,0,ifelse(by_construction_empirical$coef=="RC"&by_construction_empirical$ROI==2,1,by_construction_empirical$ROI)))
by_construction_empirical$Region_of_Interest <- factor(by_construction_empirical$ROI,levels=c(0,1,2),labels=c("Critical Word","Critical+1 (word following critical word)","Critical+2"))



ggplot(by_construction_empirical, aes(x=Region_of_Interest, y=mean, fill=Region_of_Interest))+
  ylim(-25,225)+
  geom_bar(stat="identity",position = position_dodge(width=1))+
  scale_fill_manual(values = c("royalblue3","tan2","forestgreen"))+ylab("Empirical effect size (ms)")+
  theme_minimal()+
  geom_errorbar(aes(ymin=lower,
                    ymax=upper),
                position = position_dodge(width = 1),
                width = 0.2,size=1)+xlab("Effect of interest")+
  #scale_x_discrete(labels=c("Main verb /\n reduced relative","Direct object /\n sentential complement","Transitive /\n intransitive","Object vs. subject\nrelative clause","High attachment","Low attachment","Agreement violation","Filler"))+
  theme(legend.position="bottom", legend.box = "horizontal",legend.text = element_text(size=15), legend.title = element_text(size=18,face="bold"),
        axis.title.y = element_text(size=18,face="bold"),
        axis.title.x = element_blank(),
        axis.text.y=element_text(size=15),
        axis.text.x=element_blank(),
        strip.text = element_text(size=12,face="bold"))+
  geom_hline(yintercept = 0, linetype='dashed')+
  facet_wrap(~EOI,nrow=1)
ggsave('./pdfs/SI_EOI_ROI2.pdf', width=15,height=7)
```

